trigger:
- main

pool:
  vmImage: ubuntu-latest

container: ubuntu:22.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    docker info
  displayName: 'Run a multi-line script'
