trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:

  - job: build_image
    displayName: Build Docker image

    container: ubuntu:22.04

    variables:
      DOCKER_BUILDKIT: 1

    steps:
    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 20.10.17
        releaseType: stable

    - script: |
        docker info
      displayName: 'Docker: info'

    - task: Docker@2
      displayName: 'Docker: login'
      inputs:
        command: login
        containerRegistry: 'GitHub Packages'

    - script: |
        docker pull ghcr.io/flcdrg/azure-pipelines-container-jobs:latest
      displayName: 'Docker: pull'

    - script: |
        docker inspect ghcr.io/flcdrg/azure-pipelines-container-jobs:latest
      displayName: 'Docker: inspect'

    - task: Docker@2
      displayName: 'Docker: build'
      inputs:
        containerRegistry: 'GitHub Packages'
        repository: 'flcdrg/azure-pipelines-container-jobs'
        command: 'build'
        Dockerfile: 'Dockerfile'
        arguments: '--build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ghcr.io/flcdrg/azure-pipelines-container-jobs:latest'
        tags: 'latest'

    - task: Docker@2
      displayName: 'Docker: push'
      inputs:
        containerRegistry: 'GitHub Packages'
        repository: 'flcdrg/azure-pipelines-container-jobs'
        command: 'push'
        tags: 'latest'

    - script: |
        docker run --rm ghcr.io/flcdrg/azure-pipelines-container-jobs:latest dotnet --info
      displayName: Run

  - job: use_image
    displayName: Use image
    dependsOn: build_image
    container:
      image: ghcr.io/flcdrg/azure-pipelines-container-jobs:latest
      endpoint: 'GitHub Packages'

    steps:
      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          dockerVersion: 20.10.17
          releaseType: stable

      - script: |
          dotnet --info
          docker info