parameters:
  - name: dockerVersion
    displayName: 'Docker Version'
    type: string
    default: '20.10.17'

  - name: dotnetVersion
    displayName: '.NET Version'
    type: string
    default: '6.0.302'

  - name: powershellVersion
    displayName: 'PowerShell Version'
    type: string
    default: '7.2.5'

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:

  - job: build_image
    displayName: Build Docker image

    # This job could run in a container too, but not absolutely necessary
    # container: mcr.microsoft.com/dotnet/sdk:6.0-focal # This has PowerShell

    variables:
      DOCKER_BUILDKIT: 1

    steps:
    - task: PowerShell@2
      inputs:
        filePath: "scripts/Test-ChangesMadeInPath.ps1"
        arguments: >-
          -authorisation "Bearer $(system.accesstoken)" 
          -pathFilter "build/containers" 
          -buildId $(Build.BuildId)
          -collectionUri "$(System.CollectionUri)"
          -project "$(System.TeamProject)"
      env:
        SYSTEM_ACCESSTOKEN: $(system.accesstoken)

    - task: DockerInstaller@0
      displayName: Docker Installer
      condition: eq(variables['filesUpdated'], 'True')
      inputs:
        dockerVersion: ${{ parameters.dockerVersion }}
        releaseType: stable

    - script: |
        docker info
      displayName: 'Docker: info'
      condition: eq(variables['filesUpdated'], 'True')

    - task: Docker@2
      displayName: 'Docker: login'
      condition: eq(variables['filesUpdated'], 'True')
      inputs:
        command: login
        containerRegistry: 'GitHub Packages'

    # If you're using a private Docker registry, docker build (with BuildKit) may have trouble
    # downloading via the --cache-from argument.
    # - script: |
    #     docker pull ghcr.io/flcdrg/azure-pipelines-container-jobs:latest
    #   displayName: 'Docker: pull'
    #   condition: eq(variables['filesUpdated'], 'True')

    - task: Docker@2
      displayName: 'Docker: build'
      condition: eq(variables['filesUpdated'], 'True')
      inputs:
        containerRegistry: 'GitHub Packages'
        repository: 'flcdrg/azure-pipelines-container-jobs'
        command: 'build'
        buildContext: 'build/containers'
        Dockerfile: 'build/containers/Dockerfile'
        arguments: '--build-arg BUILDKIT_INLINE_CACHE=1 --build-arg DOTNET_SDK_VERSION=${{ parameters.dotnetVersion }} --build-arg POWERSHELL_VERSION=${{ parameters.powershellVersion }} --cache-from ghcr.io/flcdrg/azure-pipelines-container-jobs:latest'
        tags: 'latest'

    - task: Docker@2
      displayName: 'Docker: push'
      condition: eq(variables['filesUpdated'], 'True')
      inputs:
        containerRegistry: 'GitHub Packages'
        repository: 'flcdrg/azure-pipelines-container-jobs'
        command: 'push'
        tags: 'latest'

  - job: use_image
    displayName: Use image
    dependsOn: build_image
    container:
      image: ghcr.io/flcdrg/azure-pipelines-container-jobs:latest
      endpoint: 'GitHub Packages'
      # volumes:
      #   - $(Agent.TempDirectory):/var/lib/mysql

    variables:
      Configuration: Release

    steps:
      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          dockerVersion: ${{ parameters.dockerVersion }}
          releaseType: stable

      - script: |
          printenv
          dotnet --info
          docker info
          mkdir $(Agent.TempDirectory)/stuff
          # Ensure full access
          chmod 777 $(Agent.TempDirectory)/stuff
          ls -al $(Agent.TempDirectory)
          touch $(Agent.TempDirectory)/stuff/host

          echo "Agent.TempDirectory: $(Agent.TempDirectory)"

          # Set a variable in host step, to see if we can see it on the container steps
          echo "##vso[task.setvariable variable=myVar;isreadonly=true]$(Agent.TempDirectory)"
          echo "##vso[task.setvariable variable=myVar;isreadonly=true]A$(Agent.TempDirectory)B"
        displayName: Info (host)
        target: host

      - script: |
          printenv
          dotnet --info
          docker info

          echo "myVar: $(myVar)"
          echo "Agent.TempDirectory: $(Agent.TempDirectory)"

          ls -al $(Agent.TempDirectory)
          touch $(Agent.TempDirectory)/container
          touch $(Agent.TempDirectory)/stuff/container
          ls -al $(Agent.TempDirectory)/stuff
        displayName: Info

      - script: |
          ls -al $(Agent.TempDirectory)/stuff
        displayName: List directory (host)
        target: host

      - task: DotNetCoreCLI@2
        displayName: '.NET: build'
        inputs:
          command: 'build'
          workingDirectory: src
        