trigger:
- main

pool:
  vmImage: ubuntu-latest

container: ubuntu:22.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 20.10.17
    releaseType: stable

- script: |
    docker info
  displayName: 'Docker: info'

- task: Docker@2
  displayName: 'Docker: build'
  inputs:
    repository: 'flcdrg/example'
    command: 'build'
    Dockerfile: '**/Dockerfile'