trigger:
- main

pool:
  vmImage: ubuntu-latest

container: ubuntu:22.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 20.10.17
    releaseType: stable

- script: |
    docker info
  displayName: 'Docker: info'

- task: Docker@2
  displayName: 'Docker: login'
  inputs:
    command: login
    containerRegistry: 'GitHub Packages'

- task: Docker@2
  displayName: 'Docker: build'
  inputs:
    containerRegistry: 'GitHub Packages'
    repository: 'flcdrg/azure-pipelines-container-jobs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
  